import { test, expect } from '@playwright/test';
const base='http://localhost:3002';
test('consumer branch, switching, three-choice cap, language persistence and saved interview',async({page})=>{
 await page.goto(base);await expect(page.getByRole('button',{name:'Commencer l’entretien',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Commencer l’entretien',exact:true}).click();await expect(page.locator('.field-error[role=alert]')).toContainText('Confirmez');
 await page.locator('.eligibility input').check();await page.getByRole('button',{name:'Commencer l’entretien',exact:true}).click();
 await page.getByRole('button',{name:'Continuer',exact:true}).click();await expect(page.locator('.field-error')).toHaveCount(2);
 await page.locator('#question-Q1').getByText('MBO Red',{exact:true}).click();await page.locator('#question-Q2 .answer-option').filter({hasText:'Paquet et unité'}).click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await expect(page.locator('#question-Q2b')).toBeVisible();await page.locator('#question-Q2b .answer-option').first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-Q3 .answer-option').last().click();await page.locator('#question-Q4 .answer-option').nth(1).click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-Q5 .answer-option').nth(2).click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-Q6b').getByText('Gauloises Blondes Blue',{exact:true}).click();await page.locator('#question-Q7 .answer-option').first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await expect(page.locator('#question-Q7a')).toHaveCount(0);await page.locator('#question-Q7b input').fill('2');await page.getByRole('button',{name:'Continuer',exact:true}).click();
 for(let i=0;i<3;i++)await page.locator('#question-Q8 .answer-option').nth(i).click();await expect(page.locator('#question-Q8 input:disabled')).toHaveCount(7);
 await page.locator('#question-Q9 .answer-option').first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-Q10 .answer-option').first().click();await page.locator('#question-Q11 label').nth(3).click();await page.locator('#question-Q12 .answer-option').first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.getByRole('tab',{name:'العربية'}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await page.getByRole('tab',{name:'FR',exact:true}).click();
 await page.locator('#question-Q13 .answer-option').first().click();await page.locator('#question-Q14 .answer-option').nth(1).click();await page.getByRole('button',{name:'Vérifier les réponses',exact:true}).click();
 await page.getByRole('button',{name:'Enregistrer l’entretien',exact:true}).click();await expect(page.getByRole('heading',{name:'Entretien enregistré.'})).toBeVisible();
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('jti-pulse-records-v1')!));expect(saved).toHaveLength(1);expect(saved[0].answers.Q8).toHaveLength(3);expect(saved[0].answers.Q7b).toBe('2');expect(saved[0].answers.Q7a).toBeUndefined();
 await page.reload();await page.getByRole('button',{name:/Entretiens locaux/}).click();await expect(page.locator('.record-row')).toHaveCount(1);await page.locator('.record-row').click();await expect(page.locator('.review-section')).toHaveCount(9);
});
test('retailer eighteen-SKU stock grid and capped substitution route',async({page})=>{
 await page.goto(base);await page.locator('.mode-card').filter({hasText:'Détaillant'}).click();await page.getByRole('button',{name:'Commencer l’entretien',exact:true}).click();
 await page.locator('#question-R1 input').nth(0).fill('Alger');await page.locator('#question-R1 input').nth(1).fill('Alger');await page.locator('#question-R1 input').nth(2).fill('POS-001');await page.locator('#question-R2 .answer-option').first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await expect(page.locator('#question-R3 select')).toHaveCount(18);for(let i=0;i<18;i++)await page.locator('#question-R3 select').nth(i).selectOption(i<10?'out':'full');await page.getByRole('button',{name:'Continuer',exact:true}).click();
 for(const id of ['R4','R5','R6'])await page.locator(`#question-${id} .answer-option`).first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-R7 .answer-option').last().click();await expect(page.locator('.substitution-row')).toHaveCount(8);for(let i=0;i<8;i++)await page.locator('.substitution-row').nth(i).locator('select').first().selectOption('none');await page.getByRole('button',{name:'Continuer',exact:true}).click();
 await page.locator('#question-R9 .answer-option').nth(2).click();await page.getByRole('button',{name:'Continuer',exact:true}).click();await expect(page.locator('#question-R10')).toHaveCount(0);
 for(const id of ['R16','R17'])await page.locator(`#question-${id} .answer-option`).first().click();await page.getByRole('button',{name:'Continuer',exact:true}).click();await page.locator('#question-R18 .answer-option').first().click();await page.getByRole('button',{name:'Vérifier les réponses',exact:true}).click();await page.getByRole('button',{name:'Enregistrer l’entretien',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Entretien enregistré.'})).toBeVisible();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('jti-pulse-records-v1')!));expect(Object.keys(saved[0].answers.R8)).toHaveLength(8);expect(saved[0].answers.R10).toBeUndefined();
});
