import { t } from './questionnaire';
export const copy = {
 interview:t('Nouvel entretien','New interview','مقابلة جديدة'),
 records:t('Entretiens locaux','Local interviews','المقابلات المحلية'),
 fieldwork:t('Espace terrain','Field workspace','مساحة العمل الميداني'),
 consumer:t('Consommateur','Consumer','مستهلك'),
 retailer:t('Détaillant','Retailer','بائع تجزئة'),
 minutes:t('min','min','دقائق'),
 start:t('Commencer l’entretien','Start interview','ابدأ المقابلة'),
 resume:t('Reprendre le brouillon','Resume draft','تابع المسودة'),
 gate:t('Participant fumeur, âgé de 19 ans ou plus, qui accepte de participer.','Participant is a smoker, aged 19 or over, and agrees to participate.','المشارك مدخن، عمره 19 عامًا أو أكثر، ويوافق على المشاركة.'),
 localShort:t('Sauvegarde sur cet appareil','Saved on this device','محفوظ على هذا الجهاز'),
 localError:t('Sauvegarde locale indisponible. Exportez vos réponses avant de quitter.','Local saving is unavailable. Export your answers before leaving.','الحفظ المحلي غير متاح. صدّر إجاباتك قبل المغادرة.'),
 journey:t('Votre parcours','Your journey','مسارك'),
 next:t('Continuer','Continue','تابع'),
 back:t('Retour','Back','عودة'),
 review:t('Vérifier les réponses','Review answers','راجع الإجابات'),
 save:t('Enregistrer l’entretien','Save interview','احفظ المقابلة'),
 edit:t('Modifier','Edit','عدّل'),
 required:t('Répondez à cette question pour continuer.','Answer this question to continue.','أجب عن هذا السؤال للمتابعة.'),
 eligibility:t('Confirmez les critères de participation pour commencer.','Confirm participant eligibility to begin.','أكّد شروط المشاركة للبدء.'),
 search:t('Rechercher une marque ou un produit…','Search a brand or product…','ابحث عن علامة أو منتج…'),
 noResults:t('Aucun produit trouvé. Essayez un autre nom.','No products found. Try another name.','لا توجد منتجات مطابقة. جرّب اسمًا آخر.'),
 one:t('Une réponse','One answer','إجابة واحدة'),
 multi:t('Plusieurs réponses','Multiple answers','عدة إجابات'),
 max:t('3 réponses maximum','Up to 3 answers','3 إجابات كحد أقصى'),
 specify:t('Précisez votre réponse','Please specify','اكتب إجابتك'),
 between:t('Entrez un nombre entier entre','Enter a whole number between','أدخل عددًا صحيحًا بين'),
 and:t('et','and','و'),
 unlikely:t('Très improbable','Very unlikely','غير محتمل إطلاقًا'),
 likely:t('Très probable','Very likely','محتمل جدًا'),
 wilaya:t('Wilaya','Wilaya','الولاية'),
 city:t('Ville','City','المدينة'),
 pos:t('Identifiant du point de vente','Point-of-sale ID','معرّف نقطة البيع'),
 primary:t('Alternative la plus fréquente','Most common substitute','البديل الأكثر شيوعًا'),
 secondary:t('Si ce choix est indisponible · facultatif','If this is unavailable · optional','إذا لم يتوفر هذا البديل · اختياري'),
 select:t('Sélectionner…','Select…','اختر…'),
 otherBrand:t('Autre marque, à préciser','Other brand, specify','علامة أخرى'),
 none:t('Aucun substitut / repart sans achat','No clear substitute / leaves without buying','لا بديل واضح / يغادر دون شراء'),
 flagged:t('Uniquement les références en rupture ou disponibles à l’unité. Maximum 8, par ordre de priorité.','Only out-of-stock or stick-only variants. Up to 8, in sales rank order.','المنتجات غير المتوفرة أو المتوفرة بالسيجارة فقط. حتى 8 حسب ترتيب المبيعات.'),
 photoPending:t('Photo à ajouter','Photo pending','الصورة غير متاحة'),
 bridgeError:t('Enregistré sur cet appareil. Transmission à l’application indisponible.','Saved on this device. Transfer to the app is unavailable.','حُفظت المقابلة على هذا الجهاز. تعذّر إرسالها إلى التطبيق.'),
 retry:t('Réessayer l’envoi','Retry sending','أعد محاولة الإرسال'),
 success:t('Entretien enregistré.','Interview saved.','تم حفظ المقابلة.'),
 export:t('Exporter les entretiens','Export interviews','صدّر المقابلات'),
 exportDraft:t('Exporter le brouillon','Export draft','صدّر المسودة'),
 new:t('Nouvel entretien','New interview','مقابلة جديدة'),
 empty:t('Aucun entretien','No interviews yet','ابدأ أول مقابلة'),
 recorded:t('enregistré(s) sur cet appareil','saved on this device','محفوظة على هذا الجهاز'),
 completed:t('Terminé','Complete','مكتملة'),
 catalogue:t('Références de l’étude','Study catalogue','منتجات الدراسة'),
 progress:t('Progression','Progress','التقدم'),
 home:t('Accueil','Home','الرئيسية'),
};
