import { t } from './questionnaire';
export const copy = {
 overview:t('Vue d’ensemble','Overview','نظرة عامة'), interview:t('Nouvel entretien','New interview','مقابلة جديدة'), records:t('Entretiens locaux','Local interviews','المقابلات المحلية'), fieldwork:t('Espace terrain','Field workspace','مساحة العمل الميداني'), study:t('Étude terrain · Algérie','Field study · Algeria','دراسة ميدانية · الجزائر'),
 hero:t('Le terrain parle.','The field speaks.','الميدان يتحدث.'), heroAccent:t('Chaque réponse compte.','Every answer matters.','كل إجابة مهمة.'), intro:t('Une expérience simple pour comprendre la disponibilité des produits et les décisions d’achat.','A considered experience to understand product availability and purchase decisions.','تجربة بسيطة لفهم توفر المنتجات وقرارات الشراء.'),
 choose:t('À qui donnons-nous la parole ?','Whose perspective are we capturing?','من نُجري معه المقابلة؟'), chooseSub:t('Choisissez le parcours adapté à votre entretien.','Choose the right journey for your interview.','اختر المسار المناسب للمقابلة.'), consumer:t('Consommateur','Consumer','مستهلك'), retailer:t('Détaillant','Retailer','بائع تجزئة'), consumerDesc:t('Du produit recherché à la décision d’achat.','From purchase intent to the final decision.','من المنتج المطلوب إلى قرار الشراء.'), retailerDesc:t('Disponibilité, alternatives et tendances du point de vente.','Availability, alternatives and point-of-sale trends.','التوفر والبدائل واتجاهات نقطة البيع.'),
 minutes:t('min','min','دقائق'), references:t('références produit','product variants','منتجًا'), languages:t('langues disponibles','available languages','لغات متاحة'), journeys:t('parcours d’entretien','interview journeys','مساران للمقابلة'), start:t('Commencer l’entretien','Start interview','ابدأ المقابلة'), resume:t('Reprendre le brouillon','Resume draft','تابع المسودة'), gate:t('Je confirme que la personne interrogée est fumeuse, âgée de 19 ans ou plus, et souhaite participer à cette étude.','I confirm that the respondent is a smoker, aged 19 or over, and agrees to participate in this study.','أؤكد أن المشارك مدخن وعمره 19 عامًا أو أكثر، ويوافق على المشاركة في الدراسة.'),
 local:t('Les réponses restent sur cet appareil. Exportez vos entretiens pour les transmettre à votre équipe.','Responses stay on this device. Export your interviews to share them with your team.','تبقى الإجابات على هذا الجهاز. صدّر المقابلات لمشاركتها مع فريقك.'), localShort:t('Sauvegarde sur cet appareil','Saved on this device','محفوظ على هذا الجهاز'), localReady:t('Brouillon sauvegardé','Draft saved','تم حفظ المسودة'), localError:t('Sauvegarde locale indisponible. Exportez vos réponses avant de quitter.','Local saving is unavailable. Export your answers before leaving.','الحفظ المحلي غير متاح. صدّر إجاباتك قبل المغادرة.'),
 journey:t('Votre parcours','Your journey','مسارك'), step:t('Section','Section','القسم'), of:t('sur','of','من'), next:t('Continuer','Continue','متابعة'), back:t('Retour','Back','رجوع'), review:t('Vérifier les réponses','Review answers','راجع الإجابات'), reviewTitle:t('Un dernier regard.','One last look.','مراجعة أخيرة.'), reviewDesc:t('Vérifiez l’entretien avant de l’enregistrer sur cet appareil.','Review the interview before saving it on this device.','راجع المقابلة قبل حفظها على هذا الجهاز.'), save:t('Enregistrer l’entretien','Save interview','احفظ المقابلة'), edit:t('Modifier','Edit','تعديل'), required:t('Répondez à cette question pour continuer.','Answer this question to continue.','أجب عن هذا السؤال للمتابعة.'), eligibility:t('Confirmez les critères de participation pour commencer.','Confirm participant eligibility to begin.','أكّد شروط المشاركة للبدء.'),
 search:t('Rechercher une marque ou un produit…','Search a brand or product…','ابحث عن علامة أو منتج…'), noResults:t('Aucun produit trouvé. Essayez un autre nom.','No products found. Try another name.','لا توجد منتجات مطابقة. جرّب اسمًا آخر.'), one:t('Une réponse','One answer','إجابة واحدة'), multi:t('Plusieurs réponses','Multiple answers','عدة إجابات'), max:t('3 réponses maximum','Up to 3 answers','3 إجابات كحد أقصى'), specify:t('Précisez votre réponse','Please specify','حدّد إجابتك'), between:t('Entrez un nombre entier entre','Enter a whole number between','أدخل عددًا صحيحًا بين'), and:t('et','and','و'), unlikely:t('Très improbable','Very unlikely','غير محتمل إطلاقًا'), likely:t('Très probable','Very likely','محتمل جدًا'),
 wilaya:t('Wilaya','Wilaya','الولاية'), city:t('Ville','City','المدينة'), pos:t('Identifiant du point de vente','Point-of-sale ID','معرّف نقطة البيع'), primary:t('Alternative principale','Most common substitute','البديل الأكثر شيوعًا'), secondary:t('Deuxième choix · facultatif','Second choice · optional','الخيار الثاني · اختياري'), select:t('Sélectionner…','Select…','اختر…'), otherBrand:t('Autre marque, à préciser','Other brand, specify','علامة أخرى، حدّد'), none:t('Aucun substitut / repart sans achat','No clear substitute / leaves without buying','لا بديل واضح / يغادر دون شراء'),
 flagged:t('Uniquement les références en rupture ou disponibles à l’unité. Maximum 8, par ordre de priorité.','Only out-of-stock or stick-only variants. Up to 8, in sales rank order.','المنتجات غير المتوفرة أو المتوفرة بالسيجارة فقط. حتى 8 حسب ترتيب المبيعات.'), photoPending:t('Photo à ajouter','Photo pending','الصورة غير متاحة'),
 success:t('Entretien enregistré.','Interview saved.','تم حفظ المقابلة.'), successDesc:t('Votre réponse est conservée sur cet appareil. Vous pouvez l’exporter ou commencer un nouvel entretien.','Your response is saved on this device. Export it or start a new interview.','حُفظت إجاباتك على هذا الجهاز. يمكنك تصديرها أو بدء مقابلة جديدة.'), export:t('Exporter les entretiens','Export interviews','صدّر المقابلات'), exportDraft:t('Exporter le brouillon','Export draft','صدّر المسودة'), new:t('Nouvel entretien','New interview','مقابلة جديدة'), empty:t('Le premier entretien commence ici.','Your first interview starts here.','ابدأ أول مقابلة من هنا.'), emptyDesc:t('Vos entretiens enregistrés apparaîtront dans cet espace.','Your saved interviews will appear here.','ستظهر مقابلاتك المحفوظة هنا.'), recorded:t('enregistré(s) sur cet appareil','saved on this device','محفوظة على هذا الجهاز'), view:t('Consulter','View','عرض'), completed:t('Terminé','Complete','مكتملة'), catalogue:t('Références de l’étude','Study catalogue','منتجات الدراسة'), collected:t('Collecter avec précision.','Capture with care.','اجمع الإجابات بدقة.'), collectedDesc:t('Deux regards complémentaires pour mieux comprendre les ruptures de stock.','Two complementary perspectives to understand stock disruptions.','رؤيتان متكاملتان لفهم نقص المخزون.'), progress:t('Progression','Progress','التقدم'), home:t('Accueil','Home','الرئيسية'), savedView:t('Entretien enregistré sur cet appareil','Interview saved on this device','مقابلة محفوظة على هذا الجهاز'),
};
